version: "3.9"

services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod 
    container_name: crs-backend-app-prod
    ports:
      - "8881:8888"
    env_file:
      - .env.prod
    depends_on:
      db-prod:
        condition: service_healthy
    networks:
      - crs-app-prod-net

  db-prod:
    image: postgres:17
    container_name: crs-backend-db-prod
    env_file:
      - .env.prod
    ports:
      - "5435:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crs-prod -d crsDB-prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crs-app-prod-net

volumes:
  pgdata_prod:

networks:
  crs-app-prod-net:
    driver: bridge