version: "3.9"

services:
  app-prod:
    image: ghcr.io/${GHCR_USERNAME}/csr:latest
    container_name: crs-backend-app-prod
    expose:
      - "8888"
    env_file:
      - .env.prod
    volumes:
      - ./assets:/app/assets
    depends_on:
      db-prod:
        condition: service_healthy
    networks:
      - crs-app-prod-net

  db-prod:
    image: postgres:17
    container_name: crs-backend-db-prod
    env_file:
      - .env.prod
    ports:
      - "5435:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crs-prod -d crsDB-prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crs-app-prod-net

  nginx-prod:
    image: nginx:stable
    container_name: crs-backend-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
      - ./assets:/app/assets
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app-prod
    networks:
      - crs-app-prod-net

volumes:
  pgdata_prod:

networks:
  crs-app-prod-net:
    driver: bridge